"""SLURM backend: sbatch / squeue / sacct / scancel.

The job script calls research.runner, which writes status.json + logs into the run directory,
so status can be recovered from files even when sacct is unavailable.
"""
from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
from typing import Any, Dict, List, Optional

from ..util import ResearchError
from .base import CORE_PARENT, Backend

_SACCT_MAP = {
    "PENDING": "queued", "CONFIGURING": "queued", "REQUEUED": "queued", "RESIZING": "queued", "SUSPENDED": "queued",
    "RUNNING": "running", "COMPLETING": "running", "STAGE_OUT": "running",
    "COMPLETED": "completed",
    "FAILED": "failed", "TIMEOUT": "failed", "NODE_FAIL": "failed", "OUT_OF_MEMORY": "failed",
    "BOOT_FAIL": "failed", "DEADLINE": "failed", "PREEMPTED": "failed",
    "CANCELLED": "cancelled", "REVOKED": "cancelled",
}


def map_state(s: str) -> str:
    s = (s or "").strip().upper().split(" ")[0].rstrip("+")
    return _SACCT_MAP.get(s, "unknown")


def _run(argv: List[str], timeout: float = 30.0) -> subprocess.CompletedProcess:
    if not shutil.which(argv[0]):
        raise ResearchError(f"`{argv[0]}` not found on PATH — is SLURM available on this machine?",
                            hint="Under Remote SSH the extension runs on the remote host; check `which sbatch` there.")
    return subprocess.run(argv, capture_output=True, text=True, timeout=timeout)


def build_script(run_dir: str, command: str, cwd: str, run_id: str, opts: Dict[str, Any],
                 python: Optional[str] = None) -> str:
    L = ["#!/bin/bash", f"#SBATCH --job-name={opts.get('job_name') or run_id}",
         f"#SBATCH --output={run_dir}/slurm-%j.out"]
    if opts.get("partition"):
        L.append(f"#SBATCH --partition={opts['partition']}")
    if opts.get("account"):
        L.append(f"#SBATCH --account={opts['account']}")
    if opts.get("time"):
        L.append(f"#SBATCH --time={opts['time']}")
    if opts.get("cpus"):
        L.append(f"#SBATCH --cpus-per-task={opts['cpus']}")
    if opts.get("mem"):
        L.append(f"#SBATCH --mem={opts['mem']}")
    if opts.get("gpus"):
        g = str(opts["gpus"])
        L.append(f"#SBATCH --gres=gpu:{g}" if ":" not in g else f"#SBATCH --gres={g}")
    for a in opts.get("extra_args") or []:
        L.append(f"#SBATCH {a}")
    L += ["", "# generated by research — do not edit; re-submit instead", f"cd {shlex.quote(cwd)}"]
    for s in opts.get("setup") or []:
        L.append(str(s))
    L.append(f'export PYTHONPATH={shlex.quote(CORE_PARENT)}"${{PYTHONPATH:+:$PYTHONPATH}}"')
    py = python or opts.get("python") or sys.executable
    L.append(f"exec {shlex.quote(py)} -m research.runner --run-dir {shlex.quote(run_dir)} --cwd {shlex.quote(cwd)} -- "
             + shlex.quote(command))
    return "\n".join(L) + "\n"


class SlurmBackend(Backend):
    name = "slurm"

    def submit(self, project, run: Dict[str, Any], opts: Dict[str, Any]) -> Dict[str, Any]:
        run_dir = project.abspath(run["run_dir"])
        cwd = project.abspath(run.get("working_dir") or ".")
        merged = {**(project.config.get("backends", {}).get("slurm") or {}),
                  **{k: v for k, v in opts.items() if v not in (None, [], "")}}
        script = build_script(run_dir, run["command"], cwd, run["id"], merged)
        spath = os.path.join(run_dir, "job.sbatch")
        with open(spath, "w", encoding="utf-8") as f:
            f.write(script)
        p = _run(["sbatch", "--parsable", spath])
        if p.returncode != 0:
            raise ResearchError(f"sbatch failed: {(p.stderr or p.stdout).strip()}")
        job = p.stdout.strip().split(";")[0].strip()
        if not job:
            raise ResearchError(f"sbatch returned no job id: {p.stdout!r}")
        resources = {k: merged.get(k) for k in ("partition", "account", "time", "cpus", "mem", "gpus") if merged.get(k)}
        if merged.get("extra_args"):
            resources["extra_args"] = merged["extra_args"]
        return {"slurm_job_id": job, "slurm": {"requested": resources, "script": project.rel(spath)},
                "status": "queued"}

    def status(self, project, run: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        from ..runner import read_status
        st = read_status(project.abspath(run["run_dir"])) or {}
        if st.get("state") in ("completed", "failed", "cancelled"):
            return st
        job = run.get("slurm_job_id")
        if not job or not shutil.which("squeue"):
            return st or None
        q = _run(["squeue", "-h", "-j", str(job), "-o", "%T|%N|%S"])
        line = q.stdout.strip().splitlines()[0] if q.returncode == 0 and q.stdout.strip() else ""
        if line:
            parts = line.split("|")
            state = map_state(parts[0])
            out = {**st, "state": state, "slurm_state": parts[0]}
            if len(parts) > 1 and parts[1] and parts[1] not in ("(null)", "n/a"):
                out.setdefault("slurm_nodelist", parts[1])
            return out
        if shutil.which("sacct"):
            a = _run(["sacct", "-n", "-P", "-j", str(job), "-o", "JobID,State,ExitCode,Start,End,NodeList"])
            for row in a.stdout.strip().splitlines():
                f = row.split("|")
                if f and f[0] == str(job):
                    code = None
                    try:
                        code = int(f[2].split(":")[0])
                    except (IndexError, ValueError):
                        pass
                    state = map_state(f[1])
                    return {**st, "state": state, "exit_code": st.get("exit_code") if st.get("exit_code") is not None else code,
                            "slurm_state": f[1], "started_at": st.get("started_at") or (f[3] if len(f) > 3 and f[3] not in ("Unknown", "None") else None),
                            "ended_at": st.get("ended_at") or (f[4] if len(f) > 4 and f[4] not in ("Unknown", "None") else None),
                            "slurm_nodelist": f[5] if len(f) > 5 else None}
        # not in queue, no accounting: if the runner never finished, we don't know
        if st.get("state") in (None, "running"):
            return {**st, "state": "unknown", "note": "job left the queue without recording an exit status"}
        return st

    def cancel(self, project, run: Dict[str, Any]) -> None:
        job = run.get("slurm_job_id")
        if not job:
            raise ResearchError(f"{run['id']} has no SLURM job id")
        p = _run(["scancel", str(job)])
        if p.returncode != 0:
            raise ResearchError(f"scancel failed: {(p.stderr or p.stdout).strip()}")
