"""Project-local CLI: `.research/bin/research`.

Copies the running `research` + `research_cli` packages into `.research/bin/lib/` and writes small launchers next
to them, so any agent or shell in the project can run `.research/bin/research …` without `pip install` or a
PATH change (e.g. Claude Code's Bash tool, which does not see VS Code's terminal environment).

The copy is per machine (the launcher records this machine's Python), so `bin/` is gitignored. It is refreshed
whenever the source code differs, by `research init`, `research bin install` and the VS Code extension.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import sys
from typing import Any, Dict, List, Optional, Tuple

PACKAGES = ("research", "research_cli")
SKIP_DIRS = {"__pycache__"}
GITIGNORE_LINE = "bin/"


def bin_dir(root: str) -> str:
    return os.path.join(root, ".research", "bin")


def launcher(root: str) -> str:
    return os.path.join(bin_dir(root), "research.cmd" if os.name == "nt" else "research")


def _sources() -> List[Tuple[str, str]]:
    """(package name, source dir) for the code that is running right now."""
    import research
    out = [("research", os.path.dirname(os.path.abspath(research.__file__)))]
    try:
        import research_cli
        out.append(("research_cli", os.path.dirname(os.path.abspath(research_cli.__file__))))
    except ImportError:
        pass
    return out


def _walk(src: str):
    for d, dirs, files in os.walk(src):
        dirs[:] = sorted(x for x in dirs if x not in SKIP_DIRS)
        for f in sorted(files):
            if not f.endswith((".pyc", ".pyo")):
                yield os.path.join(d, f)


def _stamp(sources: List[Tuple[str, str]], python: str) -> str:
    h = hashlib.sha256(python.encode())
    for name, src in sources:
        for f in _walk(src):
            st = os.stat(f)
            h.update(f"{name}/{os.path.relpath(f, src)}:{st.st_size}:{int(st.st_mtime)}".encode())
    from . import __version__
    return f"{__version__}:{h.hexdigest()[:16]}"


def _sh(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def _posix_launcher(python: str) -> str:
    return f"""#!/bin/sh
# Research OS CLI for this project — generated by `research bin install` / the Research Panel extension.
# Runs the copy of the CLI in .research/bin/lib: no pip install or PATH change needed. Safe to delete;
# it is recreated automatically. Override the interpreter with RESEARCH_PYTHON=/path/to/python3.
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PY="${{RESEARCH_PYTHON:-}}"
if [ -z "$PY" ]; then
  for c in {_sh(python)} python3 python; do
    if command -v "$c" >/dev/null 2>&1; then PY="$c"; break; fi
  done
fi
if [ -z "$PY" ]; then echo "research: no Python 3 found (set RESEARCH_PYTHON)" >&2; exit 127; fi
PYTHONPATH="$HERE/lib${{PYTHONPATH:+:$PYTHONPATH}}" exec "$PY" -m research_cli "$@"
"""


def _windows_launcher(python: str) -> str:
    return (
        "@echo off\r\n"
        "rem Research OS CLI for this project - generated by `research bin install` / the Research Panel extension.\r\n"
        "setlocal\r\n"
        "set \"PY=%RESEARCH_PYTHON%\"\r\n"
        f"if \"%PY%\"==\"\" if exist \"{python}\" set \"PY={python}\"\r\n"
        "if \"%PY%\"==\"\" set \"PY=python\"\r\n"
        "set \"PYTHONPATH=%~dp0lib;%PYTHONPATH%\"\r\n"
        "\"%PY%\" -m research_cli %*\r\n"
    )


def _ensure_gitignored(root: str) -> None:
    gi = os.path.join(root, ".research", ".gitignore")
    try:
        text = open(gi, encoding="utf-8").read() if os.path.exists(gi) else ""
    except OSError:
        return
    if any(line.strip() in (GITIGNORE_LINE, "/bin/", "bin") for line in text.splitlines()):
        return
    with open(gi, "a", encoding="utf-8") as f:
        f.write(("" if not text or text.endswith("\n") else "\n")
                + "# project-local CLI (per machine, recreated automatically)\n" + GITIGNORE_LINE + "\n")


def status(root: str) -> Dict[str, Any]:
    path = launcher(root)
    stamp_file = os.path.join(bin_dir(root), "lib", ".stamp")
    stamp = open(stamp_file).read().strip() if os.path.exists(stamp_file) else None
    return {"path": path, "exists": os.path.exists(path), "stamp": stamp}


def install(root: str, python: Optional[str] = None, force: bool = False) -> Dict[str, Any]:
    """Create or refresh `.research/bin/`. Cheap when nothing changed (compares a stamp, copies nothing)."""
    python = python or sys.executable or "python3"
    sources = _sources()
    bdir = bin_dir(root)
    lib = os.path.join(bdir, "lib")
    stamp = _stamp(sources, python)
    stamp_file = os.path.join(lib, ".stamp")
    posix, win = os.path.join(bdir, "research"), os.path.join(bdir, "research.cmd")
    current = os.path.exists(stamp_file) and open(stamp_file).read().strip() == stamp
    _ensure_gitignored(root)
    if current and not force and os.path.exists(posix) and os.path.exists(win):
        return {"path": launcher(root), "updated": False, "stamp": stamp}
    os.makedirs(bdir, exist_ok=True)
    tmp = lib + ".tmp"
    shutil.rmtree(tmp, ignore_errors=True)
    for name, src in sources:
        for f in _walk(src):
            dst = os.path.join(tmp, name, os.path.relpath(f, src))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(f, dst)
    with open(os.path.join(tmp, ".stamp"), "w") as f:
        f.write(stamp + "\n")
    old = lib + ".old"
    shutil.rmtree(old, ignore_errors=True)
    if os.path.exists(lib):
        os.replace(lib, old)
    os.replace(tmp, lib)
    shutil.rmtree(old, ignore_errors=True)
    with open(posix, "w", newline="\n") as f:
        f.write(_posix_launcher(python))
    os.chmod(posix, 0o755)
    with open(win, "w", newline="") as f:
        f.write(_windows_launcher(python))
    return {"path": launcher(root), "updated": True, "stamp": stamp}
