/**
 * Makes the bundled CLI available as `research` in VS Code terminals (including terminals that
 * coding agents use), without requiring `pip install`. The shim lives in the extension's global
 * storage on the machine running the extension host (the remote host under Remote SSH).
 */
import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

export class Shim {
  binDir: string;
  script: string;
  onPath = false;

  constructor(private ctx: vscode.ExtensionContext, private python: string, private pythonPath: string) {
    this.binDir = path.join(ctx.globalStorageUri.fsPath, 'bin');
    this.script = path.join(this.binDir, 'research');
  }

  install(enabled: boolean) {
    const coll = this.ctx.environmentVariableCollection;
    coll.clear();
    if (process.platform === 'win32') return;
    try {
      fs.mkdirSync(this.binDir, { recursive: true });
      const body = `#!/bin/sh\n# Generated by the Research Panel VS Code extension. Runs the bundled research CLI.\nPYTHONPATH=${sh(this.pythonPath)}\${PYTHONPATH:+:\$PYTHONPATH} exec ${sh(this.python)} -m research_cli "$@"\n`;
      if (!fs.existsSync(this.script) || fs.readFileSync(this.script, 'utf8') !== body) {
        fs.writeFileSync(this.script, body, { mode: 0o755 });
      }
      fs.chmodSync(this.script, 0o755);
      this.onPath = enabled;
      if (enabled) {
        coll.description = 'Adds the `research` CLI to PATH';
        coll.prepend('PATH', this.binDir + path.delimiter);
      }
    } catch (e) {
      /* non-fatal */
    }
  }

  env(): Record<string, string> {
    return process.platform === 'win32' ? {} : { PATH: this.binDir + path.delimiter + (process.env.PATH || '') };
  }

  /** Shell-quoted invocation of the CLI (absolute path, so it works even if PATH was not updated). */
  commandLine(args: string[]): string {
    // `research` resolves through the PATH we inject into the terminal; fall back to the absolute shim path.
    const exe = process.platform === 'win32' ? `${sh(this.python)} -m research_cli` : this.onPath ? 'research' : sh(this.script);
    return [exe, ...args.map(sh)].join(' ');
  }
}

export function sh(s: string): string {
  if (/^[\w@%+=:,./-]+$/.test(s)) return s;
  return `'${s.replace(/'/g, `'\\''`)}'`;
}
